// Actual SQLite, synthetic Goals only. No desktop database, Provider, App or network.
import { afterEach, beforeAll, describe, expect, test } from "vitest";
import { CANONICAL_GOAL_SNAPSHOT_SQL, projectCanonicalGoalSnapshot, readCanonicalGoalSnapshot } from "@/lib/goal-snapshot";
import { createGoalQuotaAuthority, GOAL_QUOTA_SQL } from "@/lib/db-goal-quota";
import { GOAL_QUOTA_PROTOCOL } from "@/core/goal-quota";
import { normalizeTurn } from "@/decision/session";
import { emptyEvidence } from "@/decision/evidence";
import type { GoalRound } from "@/decision/goal";
import { asDb, loadSqlite, migratedDb, placeholdersAscend, type RawDb, type SqliteModule } from "./sqlite-helper";
let sqlite:SqliteModule;const owned:RawDb[]=[];
beforeAll(async()=>{const mod=await loadSqlite();expect(mod,"Actual SQLite required; this proof must not skip").not.toBeNull();sqlite=mod!;});
afterEach(()=>{for(const raw of owned.splice(0))(raw as RawDb&{close():void}).close();});
const goalId="goal-alpha",enrollmentId="enroll-alpha",taskId="task-alpha",executionId="exec-alpha",ownerId="owner-alpha";
const id={goalId,enrollmentId};
const execution={owner_id:ownerId,fence:1,task_id:taskId,execution_id:executionId};
const call={permitId:"permit-one",kind:"main" as const,purpose:"answer" as const};
function round(final=false,terminal=false):GoalRound {
 const cp=normalizeTurn({id:taskId,seq:1,goal:"synthetic private prompt sentinel",status:final?"completed":"running",summary:null,events:[{type:"run_start",runId:"run-alpha",goal:"synthetic prompt sentinel",model:"synthetic-model-sentinel"},...(terminal?[{type:"run_end",status:"completed",summary:"synthetic final summary sentinel"}]:[])],lock:"synthetic-model-sentinel",permission:"confirm",files:["/synthetic/private/path-sentinel"],multi:false,startedAt:1000,endedAt:final?2000:null,goalId,mode:"quick",preference:"balanced",preferenceSource:"global",recovery_accounting:{version:1,task_id:taskId,run_id:"run-alpha",llm_calls:1,final}});
 return {index:1,title:"synthetic prompt sentinel",items:[],status:"running",evidence:emptyEvidence(),verdict:null,task_id:taskId,task_checkpoint:cp,llm_settlements:[],started_at:1000,finished_at:null};
}
function fixture(){
 const raw=migratedDb(sqlite);owned.push(raw);const db=asDb(()=>raw),authority=createGoalQuotaAuthority(db,()=>1000);
 const envelope=(rounds:GoalRound[]=[],e:typeof execution|undefined=undefined,revision=0)=>({protocol:GOAL_QUOTA_PROTOCOL,goal_id:goalId,enrollment_id:enrollmentId,revision,rounds,...(e?{execution:{...e}}:{})});
 const insert=async(gid=goalId,eid=enrollmentId,body:unknown=envelope(),status="idle")=>{await createGoalQuotaAuthority(db,()=>1000).prepareNew({goalId:gid,enrollmentId:eid,limit:3});await db.execute("INSERT INTO goals (id,description,max_llm_calls,used_llm_calls,status,rounds,created_at,updated_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8)",[gid,"synthetic private description sentinel",3,0,status,JSON.stringify(body),1000,1000]);};
 const update=async(body:unknown,status="running")=>db.execute("UPDATE goals SET rounds=$1,status=$2 WHERE id=$3",[typeof body==="string"?body:JSON.stringify(body),status,goalId]);
 const active=async(rounds:GoalRound[]=[round()])=>{await insert(goalId,enrollmentId,envelope(),"running");const claim=await authority.claim({...id,ownerId,expectedFence:0,leaseMs:300000});await update(envelope(rounds,execution,1));return claim;};
 const record=()=>authority.snapshot(id);
 const overwrite=(x:unknown)=>db.execute("UPDATE app_meta SET value=$1 WHERE key=$2",[typeof x==="string"?x:JSON.stringify(x),`goal-quota:v1:${goalId}`]);
 const ledger=(tid=taskId,key="eg-parent",state="started")=>db.execute("INSERT INTO tool_invocations(idempotency_key,task_id,step_id,invocation_id,tool,args_digest,attempt,state,artifacts,detail,lease_owner,lease_expires_at,created_at,updated_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14)",[key,tid,"s1",`${tid}:s1:1`,"synthetic-model-tool-sentinel","synthetic-args-digest-sentinel",1,state,JSON.stringify([{kind:"file",action:"move",path:"/synthetic/private/source-sentinel",to:"/synthetic/private/destination-sentinel",ok:true}]),"synthetic raw detail sentinel","run-ledger-owner",31000,1000,1000]);
 return {raw,db,authority,envelope,insert,update,active,record,overwrite,ledger};
}
const invalid=(p:Promise<unknown>,code="quota_protocol_invalid")=>expect(p).rejects.toMatchObject({name:"GoalQuotaControlError",code,message:code});
describe("strict canonical V1 evidence snapshot on actual migrated SQLite",()=>{
 test("fresh prepared Goal has explicit identity, schema7 and no fabricated execution or receipt",async()=>{const f=fixture();await f.insert();const s=await readCanonicalGoalSnapshot(f.db,goalId),p=projectCanonicalGoalSnapshot(s);expect(s.schemaVersion).toBe(7);expect(s.envelope.revision).toBe(0);expect(s.authority.state).toBe("prepared");expect(s.toolLedger).toEqual([]);expect(p.mainReceipt.state).toBe("absent");expect(p.execution).toBeNull();expect(p.authorizesResume).toBe(false);});
 test("explicit requested Goal is chosen even when a foreign Goal precedes it",async()=>{const f=fixture();await f.insert("goal-before","enroll-before",{...f.envelope(),goal_id:"goal-before",enrollment_id:"enroll-before"});await f.insert();expect((await readCanonicalGoalSnapshot(f.db,goalId)).goalId).toBe(goalId);});
 test("active owner, canonical occupancy and raw checkpoint are observed without writes",async()=>{const f=fixture(),c=await f.active();await f.authority.meter(c,{taskId,executionId}).invoke(call,async()=>"synthetic");await f.ledger();const before=f.raw.prepare("SELECT total_changes() n").get({});f.raw.exec("PRAGMA query_only=ON");let reads=0;const s=await readCanonicalGoalSnapshot({select:async<T>(sql:string,b?:unknown[])=>{reads++;return f.db.select<T>(sql,b);}},goalId);expect(reads).toBe(1);expect(f.raw.prepare("SELECT total_changes() n").get({})).toEqual(before);expect(s.authority.active).toBe(true);expect(s.authority.lease_until).toBe(301000);expect(s.authority.consumed).toBe(1);expect(s.toolLedger[0].lease_owner).toBe("run-ledger-owner");expect(s.envelope.rounds[0].task_checkpoint?.status).toBe("running");});
 test("actual pending admission is occupied and is separate from an incomplete main receipt",async()=>{const f=fixture(),c=await f.active();await f.db.execute(GOAL_QUOTA_SQL.admit,[`goal-quota:v1:${goalId}`,goalId,enrollmentId,c.ownerId,c.fence,1000,"permit-one",taskId,executionId,"main","answer"]);const p=projectCanonicalGoalSnapshot(await readCanonicalGoalSnapshot(f.db,goalId));expect(p.authority.consumed).toBe(1);expect(p.authority.pending).toBe(1);expect(p.authority.unknown).toBe(0);expect(p.currentExecutionPermits.mainPending).toBe(1);expect(p.mainReceipt.state).toBe("incomplete");expect(p.authorizesResume).toBe(false);});
 test("actual unknown callback preserves occupied slot and accepts the fenced inactive observation",async()=>{const f=fixture(),c=await f.active();await invalid(f.authority.meter(c,{taskId,executionId}).invoke(call,async()=>{throw Error("synthetic network uncertainty");}),"quota_outcome_unknown");const s=await readCanonicalGoalSnapshot(f.db,goalId),p=projectCanonicalGoalSnapshot(s);expect(s.envelope.execution?.fence).toBe(1);expect(p.authority.fence).toBe(2);expect(p.authority.active).toBe(false);expect(p.authority.ownerId).toBeNull();expect(p.authority.consumed).toBe(1);expect(p.authority.unknown).toBe(1);expect(p.currentExecutionPermits.mainUnknown).toBe(1);expect(p.mainReceipt.state).toBe("incomplete");});
 test("positive terminal permit plus final=false stays a known charge and incomplete receipt",async()=>{const f=fixture(),c=await f.active();await f.authority.meter(c,{taskId,executionId}).invoke(call,async()=>"positive terminal");const p=projectCanonicalGoalSnapshot(await readCanonicalGoalSnapshot(f.db,goalId));expect(p.authority.succeeded).toBe(1);expect(p.authority.pending+p.authority.unknown).toBe(0);expect(p.currentExecutionPermits.mainTerminal).toBe(1);expect(p.mainReceipt).toEqual({state:"incomplete",llmCalls:1,terminalEvidence:false});expect(p.authorizesResume).toBe(false);});
 test("positive final receipt requires matching real run anchors, not just a boolean",async()=>{const f=fixture(),c=await f.active([round(true,true)]);await f.authority.meter(c,{taskId,executionId}).invoke(call,async()=>"terminal");const p=projectCanonicalGoalSnapshot(await readCanonicalGoalSnapshot(f.db,goalId));expect(p.mainReceipt).toEqual({state:"final",llmCalls:1,terminalEvidence:true});expect(p.authorizesResume).toBe(false);});
 test("absence of main checkpoint does not make settled canonical permits a final receipt",async()=>{const f=fixture(),r=round();delete r.task_checkpoint;const c=await f.active([r]);await f.authority.meter(c,{taskId,executionId}).invoke(call,async()=>"terminal");const p=projectCanonicalGoalSnapshot(await readCanonicalGoalSnapshot(f.db,goalId));expect(p.authority.consumed).toBe(1);expect(p.mainReceipt.state).toBe("absent");});
 test("normal pause's newer authority fence does not invalidate the old execution evidence",async()=>{const f=fixture(),c=await f.active();await f.authority.pause(c);await f.update(f.envelope([round()],execution,2),"paused");const s=await readCanonicalGoalSnapshot(f.db,goalId);expect(s.envelope.execution?.fence).toBe(1);expect(s.authority.fence).toBe(2);expect(s.authority.active).toBe(false);});
 test("completed checkpoint plus verifier unknown remains observable without allowing model continuation",async()=>{const f=fixture(),c=await f.active([round(true,true)]);await f.authority.meter(c,{taskId,executionId}).invoke(call,async()=>"main terminal");await invalid(f.authority.meter(c,{taskId,executionId}).invoke({...call,permitId:"permit-verifier",kind:"goal_verifier",purpose:"check_done"},async()=>{throw Error("synthetic verifier uncertainty");}),"quota_outcome_unknown");const p=projectCanonicalGoalSnapshot(await readCanonicalGoalSnapshot(f.db,goalId));expect(p.mainReceipt.state).toBe("final");expect(p.authority.unknown).toBe(1);expect(p.currentExecutionPermits.mainUnknown).toBe(0);expect(p.authorizesResume).toBe(false);});
 test("foreign ledger and child task namespaces never enter the exact current task ledger",async()=>{const f=fixture();await f.active();await f.ledger(taskId,"eg-parent");await f.ledger("task-foreign","eg-foreign","unknown");await f.ledger(`${taskId}:child:worker-one`,"eg-child","applied");await f.ledger(`${taskId}-suffix`,"eg-prefix","conflict");const s=await readCanonicalGoalSnapshot(f.db,goalId);expect(s.toolLedger.map(x=>x.idempotency_key)).toEqual(["eg-parent"]);expect(projectCanonicalGoalSnapshot(s).toolLedger).toEqual({exactTaskId:taskId,total:1,states:{planned:0,started:1,applied:0,not_applied:0,unknown:0,conflict:0}});});
 test("a single SELECT retains one revision/execution/ledger view across a concurrent committed update",async()=>{const f=fixture();await f.active();await f.ledger();let reads=0;const wrapped={select:async<T>(sql:string,b?:unknown[])=>{reads++;const rows=await f.db.select<T>(sql,b);await f.authority.pause({...id,ownerId,fence:1});await f.update(f.envelope([{...round(),task_id:"task-beta",task_checkpoint:normalizeTurn({...round().task_checkpoint!,id:"task-beta",recovery_accounting:null})}],{...execution,task_id:"task-beta",execution_id:"exec-beta"},2),"paused");await f.ledger("task-beta","eg-beta","applied");return rows;}};const old=await readCanonicalGoalSnapshot(wrapped,goalId);expect(reads).toBe(1);expect(old.envelope.revision).toBe(1);expect(old.envelope.execution?.task_id).toBe(taskId);expect(old.authority.active).toBe(true);expect(old.toolLedger.map(x=>x.idempotency_key)).toEqual(["eg-parent"]);const fresh=await readCanonicalGoalSnapshot(f.db,goalId);expect(fresh.envelope.revision).toBe(2);expect(fresh.envelope.execution?.task_id).toBe("task-beta");expect(fresh.authority.active).toBe(false);expect(fresh.toolLedger.map(x=>x.idempotency_key)).toEqual(["eg-beta"]);});
 test.each(["goal-absent","goal-deleted"])("missing/deleted explicit Goal refuses %s instead of choosing another row",async gid=>{const f=fixture();await f.insert();if(gid==="goal-deleted"){await f.insert(gid,"enroll-deleted",{...f.envelope(),goal_id:gid,enrollment_id:"enroll-deleted"});await f.db.execute("UPDATE goals SET deleted_at='synthetic' WHERE id=$1",[gid]);}await invalid(readCanonicalGoalSnapshot(f.db,gid));});
 test.each([undefined,"../goal-alpha","goal-alpha/path"])("bad explicit identity fails before DB (%s)",async x=>{let reads=0;await invalid(readCanonicalGoalSnapshot({select:async<T>()=>{reads++;return[] as T;}},x as string),"quota_invalid_request");expect(reads).toBe(0);});
 test("legacy arrays are rejected, even with a prepared authority present",async()=>{const f=fixture();await f.insert();await f.update("[]");await invalid(readCanonicalGoalSnapshot(f.db,goalId));});
 test("missing authority is never guessed from deprecated Goal counters",async()=>{const f=fixture();await f.insert();await f.db.execute("DELETE FROM app_meta WHERE key=$1",[`goal-quota:v1:${goalId}`]);await f.db.execute("UPDATE goals SET used_llm_calls=2 WHERE id=$1",[goalId]);await invalid(readCanonicalGoalSnapshot(f.db,goalId));});
 test.each(["malformed","wrong_enrollment","fractional_consumed","extra_key","missing_permit","duplicate_permit","unknown_state"])("canonical production SQL rejects corrupt authority %s",async kind=>{const f=fixture(),c=await f.active();await f.authority.meter(c,{taskId,executionId}).invoke(call,async()=>"terminal");const q=await f.record();const mutation:Record<string,unknown>={...q};if(kind==="malformed")await f.overwrite("{bad");else{if(kind==="wrong_enrollment")mutation.enrollment_id="enroll-foreign";if(kind==="fractional_consumed")mutation.consumed=0.5;if(kind==="extra_key")mutation.unapproved=true;if(kind==="missing_permit")mutation.permits=[];if(kind==="duplicate_permit"){mutation.permits=[q.permits[0],q.permits[0]];mutation.consumed=2;}if(kind==="unknown_state")mutation.state="foreign";await f.overwrite(mutation);}await invalid(readCanonicalGoalSnapshot(f.db,goalId));});
 test.each(["goal_identity","enrollment_identity","revision","round_task","checkpoint_goal","checkpoint_task","checkpoint_accounting_task","execution_owner","execution_fence","execution_task","lossy_round"])("invalid V1 identity/shape refuses normalization (%s)",async kind=>{const f=fixture();await f.active();const e=f.envelope([round()],execution,1) as unknown as Record<string,unknown>,rs=e.rounds as Record<string,unknown>[],r=rs[0],cp=r.task_checkpoint as Record<string,unknown>,ex=e.execution as Record<string,unknown>;if(kind==="goal_identity")e.goal_id="goal-foreign";if(kind==="enrollment_identity")e.enrollment_id="enroll-foreign";if(kind==="revision")e.revision=1.5;if(kind==="round_task")r.task_id="task-foreign";if(kind==="checkpoint_goal")cp.goalId="goal-foreign";if(kind==="checkpoint_task")cp.id="task-foreign";if(kind==="checkpoint_accounting_task")(cp.recovery_accounting as Record<string,unknown>).task_id="task-foreign";if(kind==="execution_owner")ex.owner_id="owner-foreign";if(kind==="execution_fence")ex.fence=2;if(kind==="execution_task")ex.task_id="task-foreign";if(kind==="lossy_round")delete r.title;await f.update(e);await invalid(readCanonicalGoalSnapshot(f.db,goalId));});
 test("authority claimed before envelope binding refuses active observation",async()=>{const f=fixture();await f.insert(goalId,enrollmentId,f.envelope(),"running");await f.authority.claim({...id,ownerId,expectedFence:0,leaseMs:300000});await invalid(readCanonicalGoalSnapshot(f.db,goalId));});
 test("final=true without matching run_end cannot become a final evidence receipt",async()=>{const f=fixture();await f.active([round(true,false)]);await invalid(readCanonicalGoalSnapshot(f.db,goalId));});
 test("a later run_start prevents an older run_end from validating a final receipt",async()=>{const f=fixture(),x=round(true,true);x.task_checkpoint!.events.push({type:"run_start",runId:"run-beta"});await f.active([x]);await invalid(readCanonicalGoalSnapshot(f.db,goalId));});
 test.each(["invalid_status","missing_summary"])("malformed run_end is not positive terminal evidence (%s)",async kind=>{const f=fixture(),x=round(true,true),end=x.task_checkpoint!.events[1] as Record<string,unknown>;if(kind==="invalid_status")end.status="untrusted-status";else delete end.summary;await f.active([x]);await invalid(readCanonicalGoalSnapshot(f.db,goalId));});
 test("returned nested identities are frozen before public projection",async()=>{const f=fixture();await f.active();const s=await readCanonicalGoalSnapshot(f.db,goalId);expect(Object.isFrozen(s.authority)).toBe(true);expect(Object.isFrozen(s.envelope.execution)).toBe(true);expect(()=>{s.envelope.execution!.task_id="task-mutated";}).toThrow();expect(projectCanonicalGoalSnapshot(s).execution?.task_id).toBe(taskId);});
 test("old schema marker and missing physical lease index are refused",async()=>{const f=fixture();await f.insert();await f.db.execute("UPDATE app_meta SET value='6' WHERE key='schema_version'");await invalid(readCanonicalGoalSnapshot(f.db,goalId));await f.db.execute("UPDATE app_meta SET value='7' WHERE key='schema_version'");f.raw.exec("DROP INDEX tool_invocations_lease");await invalid(readCanonicalGoalSnapshot(f.db,goalId));});
 test("invalid selected ledger is rejected rather than skipped or repaired",async()=>{const f=fixture();await f.active();await f.ledger();await f.db.execute("UPDATE tool_invocations SET artifacts='not-json' WHERE task_id=$1",[taskId]);await invalid(readCanonicalGoalSnapshot(f.db,goalId));});
 test("public projection contains no raw prompt/model/tool/args/artifact/path/event details",async()=>{const f=fixture();await f.active();await f.ledger();const s=await readCanonicalGoalSnapshot(f.db,goalId),publicRaw=JSON.stringify(projectCanonicalGoalSnapshot(s));expect(s.toolLedger[0].artifacts).toContain("source-sentinel");for(const word of ["prompt sentinel","model-sentinel","tool-sentinel","digest-sentinel","source-sentinel","destination-sentinel","detail sentinel","path-sentinel"])expect(publicRaw).not.toContain(word);expect(publicRaw).not.toContain("events");});
 test("SQLite read failure is a fixed redacted error and no repair/write is attempted",async()=>{const f=fixture();await f.insert();f.raw.exec("DROP TABLE tool_invocations");await invalid(readCanonicalGoalSnapshot(f.db,goalId),"quota_storage_unknown");});
 test("SQLx-compatible placeholder ordering holds for the single production SELECT",()=>{expect(placeholdersAscend(CANONICAL_GOAL_SNAPSHOT_SQL)).toBe(true);});
});
