// @vitest-environment node
import {afterEach,beforeAll,beforeEach,describe,expect,test,vi} from "vitest";
import type {Db} from "@/lib/db";
import {asDb,loadSqlite,migratedDb,type RawDb,type SqliteModule} from "./sqlite-helper";
const state=vi.hoisted(()=>({db:null as Db|null}));
vi.mock("@/lib/db",()=>({withDb:async<T>(fn:(db:Db)=>Promise<T>)=>{try{return await fn(state.db!);}catch(e){if(e&&typeof e==='object'&&'code'in e)throw{code:(e as {code:string}).code,message:(e as unknown as {message:string}).message};throw e;}}}));
import {saveGoal,updateGoal,listGoals} from "@/lib/db-goal";
import {GOAL_QUOTA_SQL} from "@/lib/db-goal-quota";
import {GoalQuotaControlError,type GoalMeterScope} from "@/core/goal-quota";
import {goalRunner} from "@/lib/goal-run";
import * as engine from "@/lib/engine";
import {createMockBackend,setBackend} from "@/platform";
import {useGoals} from "@/stores/goals";
import {useTasks} from "@/stores/tasks";
import {hydrateGoalCheckpoints} from "@/stores/history";
let sqlite:SqliteModule,raw:RawDb;
beforeAll(async()=>{sqlite=(await loadSqlite())!;expect(sqlite).not.toBeNull();});
beforeEach(()=>{raw=migratedDb(sqlite);state.db=asDb(()=>raw);const b=createMockBackend();setBackend({...b,kind:"tauri",saveGoal,updateGoal,listGoals});useGoals.setState({items:[],loaded:true,error:null});useTasks.setState({tasks:[],activeId:null});});
afterEach(()=>{for(const g of useGoals.getState().items)goalRunner.stop(g.id);vi.restoreAllMocks();setBackend(null);(raw as unknown as {close():void}).close();});
async function create(cap=4){const saved=await useGoals.getState().save({description:"synthetic inclusive host Goal",max_llm_calls:cap});if(typeof saved==='string')throw Error(saved);expect(await useGoals.getState().start(saved.id)).toBeNull();return saved.id;}
function stub(opts:{unknown?:boolean;verifierUnknown?:boolean;main?:number;decision?:number;engineFailure?:boolean;verifierRace?:boolean;snapshotFailureAfterUnknown?:boolean}={}){
 const dispatch:string[]=[],contexts:unknown[]=[],meters:GoalMeterScope[]=[];let permit=0;
 const sp=vi.spyOn(engine,"createEngine").mockImplementation(options=>{
  const o=options as typeof options & {goalMeter?:GoalMeterScope;goalExecution?:{taskId:string;executionId:string}};
  if(opts.engineFailure)throw Error("synthetic factory failure");
  if(!o.goalMeter||!o.goalExecution)throw new GoalQuotaControlError("quota_invalid_request");
  contexts.push(o.goalExecution);meters.push(o.goalMeter);
  const invoke=async(kind:"main"|"cloud_decision"|"goal_verifier",purpose:"answer"|"decision"|"check_done",failure=false)=>o.goalMeter!.invoke({permitId:`permit-host-${++permit}`,kind,purpose},async()=>{dispatch.push(kind);if(failure){
   if(opts.snapshotFailureAfterUnknown){const original=state.db!;let once=true;state.db={execute:original.execute,select:async<T>(sql:string,args?:unknown[])=>{if(sql===GOAL_QUOTA_SQL.snapshot&&once){once=false;throw Error("synthetic snapshot ACK failed");}return original.select<T>(sql,args);}};}
   throw Error("synthetic remote unknown");
  }return "synthetic";});
  const run=async(_goal:string,runOptions: {taskId?:string})=>{
   expect(runOptions.taskId).toBe(o.goalExecution!.taskId);
   const on=o.onEvent!;on({type:"run_start",runId:`run-host-${permit+1}`,goal:_goal});
   for(let n=0;n<(opts.decision??1);n++)await invoke("cloud_decision","decision");
   for(let n=0;n<(opts.main??2);n++){
    if(opts.unknown&&n===0){on({type:"llm_delta",purpose:"answer",text:"synthetic partial text",profileId:"synthetic/model"});await invoke("main","answer",true);}
    await invoke("main","answer");on({type:"llm",purpose:"answer",profileId:"synthetic/model",latencyMs:1,usage:null});
   }
   on({type:"run_end",status:"completed",summary:"synthetic complete"});return{status:"completed" as const,summary:"synthetic complete",events:[]};
  };
  return{runtime:{run},coordinator:{run},decision:{checkDoneWithEvidence:async()=>{if(opts.verifierRace)await invoke("cloud_decision","decision");await invoke("goal_verifier","check_done",opts.verifierUnknown);return{verdict:"done",by:"jev",reason:"synthetic independently observed"};}},profiles:[]} as unknown as ReturnType<typeof engine.createEngine>;
 });return{dispatch,contexts,meters,sp};
}
describe("production Tasks lazy/GoalRunner host with canonical actual SQLite; only engine transports are synthetic",()=>{
 test("new Goal shares captured parent scope across task and independent completion verifier; main receipt does not debit again",async()=>{const f=stub(),id=await create();await goalRunner.run(id);const g=useGoals.getState().items[0];expect(g.status).toBe("completed");expect(g.used_llm_calls).toBe(4);expect(f.dispatch).toEqual(["cloud_decision","main","main","goal_verifier"]);expect(f.contexts).toHaveLength(2);expect(f.contexts[0]).toEqual(f.contexts[1]);expect(f.meters[0]).toBe(f.meters[1]);expect(g.rounds[0].llm_settlements?.[0].llm_calls).toBe(2);expect(g.quota).toMatchObject({active:false,consumed:4,pending:0,unknown:0});});
 test("completed artifacts at exactly full cap have a free rules/user assessment, with no unmetered verifier",async()=>{const f=stub(),id=await create(3);await goalRunner.run(id);const g=useGoals.getState().items[0];expect(g.status).toBe("running");expect(g.rounds[0].status).toBe("uncertain");expect(g.rounds[0].verdict?.by).toBe("rules");expect(g.rounds[0].task_checkpoint?.status).toBe("completed");expect(g.quota?.consumed).toBe(3);expect(f.dispatch).toEqual(["cloud_decision","main","main"]);expect(f.sp).toHaveBeenCalledOnce();});
 test("concurrent consumption before verifier admission causes opaque denied to pause exact Task without uncertain/provider-failure fallback",async()=>{const f=stub({verifierRace:true}),id=await create(4);await goalRunner.run(id);const g=useGoals.getState().items[0];expect(g.status).toBe("paused");expect(g.rounds[0].status).toBe("interrupted");expect(g.rounds[0].verdict).toBeNull();expect(g.quota?.consumed).toBe(4);expect(f.dispatch).toEqual(["cloud_decision","main","main","cloud_decision"]);expect(useGoals.getState().error).toContain("quota_denied");});
 test("unknown model result persists bounded partial output after canonical fence advance and allows no automatic takeover",async()=>{const f=stub({unknown:true}),id=await create();await goalRunner.run(id);const g=useGoals.getState().items[0],card=useTasks.getState().tasks[0];expect(g.status).toBe("paused");expect(card.status).toBe("needs_user");expect(card.quotaControl?.code).toBe("quota_outcome_unknown");expect(g.rounds[0].task_checkpoint?.streamingText).toBe("synthetic partial text");expect(g.rounds[0].task_checkpoint?.recovery_accounting?.final).toBe(false);expect(g.rounds[0].llm_settlements??[]).toEqual([]);expect(g.quota).toMatchObject({active:false,consumed:2,unknown:1});expect(await useGoals.getState().start(id)).toBe("quota_outcome_unknown");expect(f.dispatch).toEqual(["cloud_decision","main"]);});
 test("failed exact-main snapshot retains final=false rather than exposing an early final-zero main receipt",async()=>{const f=stub({unknown:true,snapshotFailureAfterUnknown:true}),id=await create();await goalRunner.run(id);const g=(await listGoals())[0],card=useTasks.getState().tasks[0];expect(g.status).toBe("paused");expect(card.recovery_accounting?.final).toBe(false);expect(g.rounds[0].task_checkpoint?.recovery_accounting?.final).toBe(false);expect(g.rounds[0].llm_settlements??[]).toEqual([]);expect(g.quota).toMatchObject({consumed:2,unknown:1,active:false});expect(f.dispatch).toEqual(["cloud_decision","main"]);});
 test("explicit enrolled Goal Task without prepare scope resolves needs_user before engine creation, with no fabricated main receipt",async()=>{const f=stub(),id=await create();const h=useTasks.getState().runGoalRound("synthetic",{mode:"goal",goalId:id});h.start!();const r=await h.result;expect(r).toMatchObject({status:"needs_user",quotaControl:{code:"quota_invalid_request"},accounting:null});expect(f.sp).not.toHaveBeenCalled();expect((await listGoals())[0].used_llm_calls).toBe(0);});
 test("engine factory exception is inside controlled try/finally: lazy result resolves, Goal pauses, and no receipt or quota is invented",async()=>{const f=stub({engineFailure:true}),id=await create();await expect(goalRunner.run(id)).resolves.toBeUndefined();const g=useGoals.getState().items[0];expect(f.sp).toHaveBeenCalledOnce();expect(g.status).toBe("paused");expect(g.quota?.active).toBe(false);expect(g.quota?.consumed).toBe(0);expect(g.rounds[0].llm_settlements??[]).toEqual([]);expect(useTasks.getState().tasks[0].endedAt).not.toBeNull();expect(goalRunner.running(id)).toBe(false);});
 test("completed Task recovery after verifier unknown uses only free rule/user assessment and keeps occupied unknown quota",async()=>{const f=stub({verifierUnknown:true}),id=await create(4);await goalRunner.run(id);const before=(await listGoals())[0];expect(before.rounds[0].task_checkpoint?.status).toBe("completed");expect(before.quota).toMatchObject({consumed:4,unknown:1,active:false});const taskId=before.rounds[0].task_id;useTasks.setState({tasks:[]});await useGoals.getState().load();hydrateGoalCheckpoints();expect(await useGoals.getState().start(id)).toBeNull();await goalRunner.run(id);const recovered=(await listGoals())[0];expect(f.dispatch).toHaveLength(4);expect(f.sp).toHaveBeenCalledTimes(2);expect(recovered.rounds).toHaveLength(1);expect(recovered.rounds[0].task_id).toBe(taskId);expect(recovered.rounds[0].verdict?.by).toBe("rules");expect(recovered.quota).toMatchObject({consumed:4,unknown:1,active:false});});
 test("reload of another live owned Goal never invokes restart recovery or pauses its lease",async()=>{const f=stub(),id=await create();const h=useTasks.getState().runGoalRound("synthetic",{mode:"goal",goalId:id}),s=await h.prepare!();expect(s).not.toBeNull();await useGoals.getState().refresh(id);await useGoals.getState().load();expect((await listGoals())[0].quota?.active).toBe(true);expect((await listGoals())[0].status).toBe("running");expect(f.sp).not.toHaveBeenCalled();await s!.release();});
 test("competing window runner cannot implicitly pause another positively live owner after its own claim is denied",async()=>{const f=stub(),id=await create();const h=useTasks.getState().runGoalRound("synthetic",{mode:"goal",goalId:id}),s=await h.prepare!();await useGoals.getState().refresh(id);const owner=s!.publication.ownerId;await goalRunner.run(id);const g=(await listGoals())[0];expect(g.status).toBe("running");expect(g.quota?.ownerId).toBe(owner);expect(g.quota?.active).toBe(true);expect(f.sp).not.toHaveBeenCalled();await s!.release();});
 test("another window's published live round is not automatically paused by recovery discovery with missing local card/accounting",async()=>{const f=stub(),id=await create();const h=useTasks.getState().runGoalRound("synthetic",{mode:"goal",goalId:id}),session=(await h.prepare!())!;try{await useGoals.getState().apply(id,{op:"start_round",plan:{task_id:h.taskId},quota_publication:session.publication});useTasks.setState({tasks:[]});await goalRunner.run(id);const g=(await listGoals())[0];expect(g.status).toBe("running");expect(g.quota?.active).toBe(true);expect(g.quota?.ownerId).toBe(session.publication.ownerId);expect(g.quota?.fence).toBe(session.publication.fence);expect(f.sp).not.toHaveBeenCalled();}finally{await session.release();}});
 test("explicit user pause still stops positively live owner, but committed pause ACK lost is an error and cannot trigger stopper success",async()=>{const f=stub(),id=await create(),h=useTasks.getState().runGoalRound("synthetic",{mode:"goal",goalId:id}),session=(await h.prepare!())!;try{await useGoals.getState().apply(id,{op:"start_round",plan:{task_id:h.taskId},quota_publication:session.publication});const original=state.db!,stop=vi.spyOn(goalRunner,"stopAndCheckpoint");state.db={select:original.select,execute:async(sql,args)=>{const r=await original.execute(sql,args);if(sql===GOAL_QUOTA_SQL.pause)throw{code:"quota_storage_unknown",message:"quota_storage_unknown"};return r;}};expect(await useGoals.getState().pause(id)).toBe("quota_storage_unknown");expect(stop).not.toHaveBeenCalled();state.db=original;const g=(await listGoals())[0];expect(g.status).toBe("running");expect(g.quota?.active).toBe(false);expect(g.quota?.fence).toBe(session.publication.fence+1);expect(g.quota?.consumed).toBe(0);expect(f.sp).not.toHaveBeenCalled();expect(await useGoals.getState().pause(id)).toBeNull();expect((await listGoals())[0].status).toBe("paused");expect(stop).toHaveBeenCalledOnce();}finally{await session.release();}});
 test("enrollment writer failure leaves non-dispatchable orphan and never repairs it with fresh zero balance",async()=>{const current=state.db!,db:Db={select:current.select,execute:async(sql,args)=>{if(sql.startsWith("INSERT INTO goals"))throw Error("synthetic insert failure");return current.execute(sql,args);}};state.db=db;await expect(saveGoal({description:"orphan synthetic",max_llm_calls:4})).rejects.toBeDefined();state.db=current;expect(await listGoals()).toEqual([]);const rows=await state.db!.select<{key:string;value:string}[]>("SELECT key,value FROM app_meta WHERE key LIKE $1",["goal-quota:v1:%"]);expect(rows).toHaveLength(1);expect(JSON.parse(rows[0].value)).toMatchObject({state:"prepared",consumed:0,active:false});expect(goalRunner.running("goal-missing")).toBe(false);});
});
