import {beforeAll,beforeEach,afterEach,describe,expect,test,vi} from "vitest";
import type {Db} from "@/lib/db";
import {asDb,loadSqlite,migratedDb,type RawDb,type SqliteModule} from "./sqlite-helper";
const state=vi.hoisted(()=>({db:null as Db|null}));
vi.mock("@/lib/db",()=>({SCHEMA_VERSION:7,withDb:async<T>(fn:(db:Db)=>Promise<T>)=>fn(state.db!)}));
import {saveGoal,updateGoal,listGoals,getGoalForQuota,envelopeForGoal} from "@/lib/db-goal";
import {acquireGoalExecution,requireGoalSession,freeCompletedPublication,type GoalExecutionSession} from "@/lib/goal-execution";
import {GOAL_PUBLICATION_SQL,publicationArgs,strictGoalExecute} from "@/lib/db-goal-publication";
import {prepareGoalContinuation} from "@/lib/goal-continuation";
import {decodeGoalEnvelope} from "@/lib/goal-quota-storage";
import type {StoredTurn} from "@/decision/session";
let sqlite:SqliteModule,raw:RawDb;let cleanup:GoalExecutionSession[]=[];
beforeAll(async()=>{sqlite=(await loadSqlite())!;expect(sqlite).not.toBeNull();});
beforeEach(()=>{raw=migratedDb(sqlite);state.db=asDb(()=>raw);});
afterEach(async()=>{for(const s of cleanup.splice(0))await s.release().catch(()=>{});(raw as unknown as {close():void}).close();vi.restoreAllMocks();});
const now=()=>Date.now();
const get=(id:string)=>getGoalForQuota(state.db!,id);
async function running(limit=4){const g=await saveGoal({description:"synthetic Goal",max_llm_calls:limit});return updateGoal(g.id,{op:"transition",to:"running"});}
async function bound(limit=4){const g=await running(limit),s=(await acquireGoalExecution(g.id,"task-alpha"))!;cleanup.push(s);await updateGoal(g.id,{op:"start_round",plan:{task_id:"task-alpha"},quota_publication:s.publication});return{g:await get(g.id),s};}
function task(goalId:string,status="failed",calls=1,runId="run-alpha"):StoredTurn{return{id:"task-alpha",seq:1,goal:"synthetic Goal",status,summary:"synthetic partial",events:[{type:"run_start",runId,goal:"synthetic Goal"},{type:"run_end",status,summary:"synthetic partial"}],lock:null,permission:"confirm",files:[],multi:false,startedAt:now(),endedAt:now(),goalId,mode:"goal",preference:"balanced",preferenceSource:"default",recovery_accounting:{version:1,task_id:"task-alpha",run_id:runId,llm_calls:calls,final:true}};}
const call=(n:number)=>({permitId:`permit-${n}`,kind:"main" as const,purpose:"answer" as const});
describe("actual SQLite Goal execution/publication host",()=>{
 test("expired owned publication cannot authorize the before-side-effect checkpoint",async()=>{let at=10_000;vi.spyOn(Date,"now").mockImplementation(()=>at);const {g,s}=await bound();at+=300_001;let tools=0;await expect((async()=>{await updateGoal(g.id,{op:"checkpoint_round",task:task(g.id),quota_publication:s.publication});tools++;})()).rejects.toMatchObject({code:"quota_denied"});expect(tools).toBe(0);expect((await get(g.id)).rounds[0].task_checkpoint).toBeUndefined();});
 test.each(["broken","float_revision","float_fence","duplicate_execution_key","extra_root"])("malformed V1 codec never falls back to legacy; list isolates row but direct execution reports protocol error (%s)",async shape=>{const {g}=await bound();const row=(await state.db!.select<{rounds:string}[]>("SELECT rounds FROM goals WHERE id=$1",[g.id]))[0];let body=row.rounds;if(shape==="broken")body="{bad";if(shape==="float_revision")body=body.replace(/"revision":(\d+)/,'"revision":$1.0');if(shape==="float_fence")body=body.replace(/"fence":(\d+)/,'"fence":$1.0');if(shape==="duplicate_execution_key")body=body.replace('"execution_id":','"execution_id":"exec-duplicate","execution_id":');if(shape==="extra_root")body=body.slice(0,-1)+',"extra":true}';await state.db!.execute("UPDATE goals SET rounds=$1 WHERE id=$2",[body,g.id]);expect(await listGoals()).toEqual([]);await expect(get(g.id)).rejects.toMatchObject({code:"quota_protocol_invalid"});});
 test("scope claims a fresh fence, binds execution before round publication, and cannot change execution under same fence",async()=>{const g=await running();const s=(await acquireGoalExecution(g.id,"task-alpha"))!;cleanup.push(s);let n=0;expect(await s.meter.invoke(call(1),async()=>++n)).toBe(1);const cur=await get(g.id),e=envelopeForGoal(cur);e.revision++;e.execution!.execution_id="exec-other";await expect(strictGoalExecute(state.db!,GOAL_PUBLICATION_SQL.bind,publicationArgs(cur,cur,e,{...s.publication,executionId:"exec-other"},"owned",s.publication.fence))).rejects.toMatchObject({code:"quota_denied"});expect(n).toBe(1);expect((await get(g.id)).quota?.execution?.executionId).toBe(s.context.executionId);});
 test("Task requires captured exact Goal scope; absent or mismatched context cannot dispatch",async()=>{const {g,s}=await bound();await expect(requireGoalSession(g.id,"task-alpha",null)).rejects.toMatchObject({code:"quota_invalid_request"});await expect(requireGoalSession(g.id,"task-beta",s)).rejects.toMatchObject({code:"quota_invalid_request"});expect(await requireGoalSession(g.id,"task-alpha",s)).toBe(s);});
 test("main receipt records genuine recovery identity without double debit of canonical main plus independent quota",async()=>{const {g,s}=await bound();await s.meter.invoke(call(1),async()=>1);await s.meter.invoke({permitId:"permit-judge",kind:"goal_verifier",purpose:"check_done"},async()=>1);await updateGoal(g.id,{op:"checkpoint_round",task:task(g.id),quota_publication:s.publication});const result=await updateGoal(g.id,{op:"record_llm_calls",count:1,task_id:"task-alpha",run_id:"run-alpha",quota_publication:s.publication});expect(result.used_llm_calls).toBe(2);expect(result.rounds[0].llm_settlements).toEqual([{run_id:"run-alpha",llm_calls:1}]);const again=await updateGoal(g.id,{op:"record_llm_calls",count:1,task_id:"task-alpha",run_id:"run-alpha",quota_publication:s.publication});expect(again.used_llm_calls).toBe(2);});
 test("opaque unknown advances fence and still allows original partial checkpoint and final receipt, never refunds",async()=>{const {g,s}=await bound();await expect(s.meter.invoke(call(1),async()=>{throw Error("synthetic timeout");})).rejects.toMatchObject({code:"quota_outcome_unknown"});const q=(await get(g.id)).quota!;expect(q).toMatchObject({active:false,consumed:1,unknown:1,fence:s.publication.fence+1});await updateGoal(g.id,{op:"checkpoint_round",task:task(g.id,"needs_user"),quota_publication:s.publication});await updateGoal(g.id,{op:"record_llm_calls",count:1,task_id:"task-alpha",run_id:"run-alpha",quota_publication:s.publication});const stopped=await updateGoal(g.id,{op:"transition",to:"paused",quota_publication:s.publication});expect(stopped.rounds[0].task_checkpoint?.summary).toBe("synthetic partial");expect(stopped.used_llm_calls).toBe(1);await expect(updateGoal(g.id,{op:"transition",to:"running"})).rejects.toMatchObject({code:"quota_outcome_unknown"});await expect(acquireGoalExecution(g.id,"task-alpha")).rejects.toMatchObject({code:"quota_denied"});});
 test("new claim/fence invalidates old meter and every old publication, including after later owner stopped",async()=>{
  const {g,s}=await bound();
  const checkpoint=task(g.id);
  checkpoint.events.splice(1,0,{type:"plan",plan:{source:"llm",steps:[{id:"step-1",goal:"synthetic pending step",tool:null}]},revision:1});
  await updateGoal(g.id,{op:"checkpoint_round",task:checkpoint,quota_publication:s.publication});
  await updateGoal(g.id,{op:"transition",to:"paused",quota_publication:s.publication});
  await s.release();await updateGoal(g.id,{op:"transition",to:"running"});
  const continuation=await prepareGoalContinuation(g.id,"task-alpha");
  expect(continuation).not.toBeNull();
  const b=(await acquireGoalExecution(g.id,"task-alpha",Date.now,continuation!))!;cleanup.push(b);
  await updateGoal(g.id,{op:"resume_round",quota_publication:b.publication});
  let n=0;
  await expect(s.meter.invoke(call(1),async()=>++n)).rejects.toMatchObject({code:"quota_denied"});
  await expect(updateGoal(g.id,{op:"checkpoint_round",task:task(g.id,"failed",0,"run-old"),quota_publication:s.publication})).rejects.toMatchObject({code:"quota_denied"});
  await b.release();
  await expect(updateGoal(g.id,{op:"checkpoint_round",task:task(g.id,"failed",0,"run-old"),quota_publication:s.publication})).rejects.toMatchObject({code:"quota_denied"});
  expect(n).toBe(0);expect((await get(g.id)).rounds[0].task_checkpoint?.recovery_accounting?.run_id).toBe("run-alpha");
 });
 test("simultaneous publications with same expected revision commit exactly once",async()=>{const {g,s}=await bound(),e=envelopeForGoal(g);e.revision++;const next={...g,description:"published",updated_at:now()};const args=publicationArgs(g,next,e,s.publication,"owned",s.publication.fence);const results=await Promise.allSettled([strictGoalExecute(state.db!,GOAL_PUBLICATION_SQL.write,args),strictGoalExecute(state.db!,GOAL_PUBLICATION_SQL.write,args)]);expect(results.filter(r=>r.status==="fulfilled")).toHaveLength(1);expect((await get(g.id)).quota?.revision).toBe(e.revision);});
 test("new round payload cannot use a bound permit scope affiliated with another task",async()=>{const g=await running(),s=(await acquireGoalExecution(g.id,"task-alpha"))!;cleanup.push(s);await expect(updateGoal(g.id,{op:"start_round",plan:{task_id:"task-beta"},quota_publication:s.publication})).rejects.toMatchObject({code:"quota_denied"});expect((await get(g.id)).rounds).toEqual([]);});
 test("deleted Goal blocks admission even while independent canonical owner remains active",async()=>{const {g,s}=await bound();await state.db!.execute("UPDATE goals SET deleted_at=$1,status=$2 WHERE id=$3",[now(),"deleted",g.id]);let n=0;await expect(s.meter.invoke(call(1),async()=>++n)).rejects.toMatchObject({code:"quota_denied"});expect(n).toBe(0);});
 test("a missing authority or malformed versioned object is never silently read as legacy",async()=>{const g=await running();await state.db!.execute("DELETE FROM app_meta WHERE key=$1",[`goal-quota:v1:${g.id}`]);await expect(acquireGoalExecution(g.id,"task-alpha")).rejects.toMatchObject({code:"quota_protocol_invalid"});expect(()=>decodeGoalEnvelope(JSON.stringify({protocol:"inclusive-goal-quota-v1",goal_id:g.id,rounds:[]}),g.id)).toThrowError("quota_protocol_invalid");});
 test("completed persisted Task has a free rules exit with no fresh claim or model permit",async()=>{const {g,s}=await bound();await updateGoal(g.id,{op:"checkpoint_round",task:task(g.id,"completed",0),quota_publication:s.publication});await updateGoal(g.id,{op:"transition",to:"paused",quota_publication:s.publication});await s.release();await updateGoal(g.id,{op:"transition",to:"running"});const current=await get(g.id),proof=freeCompletedPublication(current,"task-alpha")!;expect(proof).not.toBeNull();await updateGoal(g.id,{op:"record_llm_calls",count:0,task_id:"task-alpha",run_id:"run-alpha",quota_publication:proof});await updateGoal(g.id,{op:"resume_round",quota_publication:proof});const completed=await updateGoal(g.id,{op:"finish_round",result:{verdict:"done",reason:"existing artifact verified",by:"rules"},evidence:current.rounds[0].evidence,quota_publication:proof});expect(completed.status).toBe("completed");expect(completed.used_llm_calls).toBe(0);expect(completed.quota?.active).toBe(false);});
 test("free completed proof cannot overwrite completed artifacts with a fresh failed task or Jev result",async()=>{const {g,s}=await bound();await updateGoal(g.id,{op:"checkpoint_round",task:task(g.id,"completed",0),quota_publication:s.publication});await s.release();const current=await get(g.id),proof=freeCompletedPublication(current,"task-alpha")!;await expect(updateGoal(g.id,{op:"checkpoint_round",task:task(g.id),quota_publication:proof})).rejects.toMatchObject({code:"quota_denied"});await expect(updateGoal(g.id,{op:"finish_round",result:{verdict:"done",reason:"not free",by:"jev"},evidence:current.rounds[0].evidence,quota_publication:proof})).rejects.toMatchObject({code:"quota_denied"});});
 test("Goal publication ACK lost is reported unknown without silently retrying",async()=>{const {g,s}=await bound(),e=envelopeForGoal(g);e.revision++;let writes=0;const faulty:Db={select:state.db!.select,execute:async(sql,args)=>{const out=await state.db!.execute(sql,args);writes++;throw Error("synthetic ACK loss");return out;}};await expect(strictGoalExecute(faulty,GOAL_PUBLICATION_SQL.write,publicationArgs(g,g,e,s.publication,"owned",s.publication.fence))).rejects.toMatchObject({code:"quota_storage_unknown"});expect(writes).toBe(1);expect((await get(g.id)).quota?.revision).toBe(e.revision);});
 test.each(["1",true,2,undefined])("publication requires positive numeric-one acknowledgement (%s)",async rowsAffected=>{let count=0;const db:Db={select:state.db!.select,execute:async()=>{count++;return{rowsAffected};}};await expect(strictGoalExecute(db,"synthetic",[])).rejects.toMatchObject({code:"quota_storage_unknown"});expect(count).toBe(1);});
 test("publication result getter exception is a typed fixed control error",async()=>{const db:Db={select:state.db!.select,execute:async()=>({get rowsAffected(){throw Error("synthetic secret");}})};await expect(strictGoalExecute(db,"synthetic",[])).rejects.toMatchObject({code:"quota_storage_unknown",message:"quota_storage_unknown"});});
});
